### PR TITLE
Update Riven Animation

### PR DESCRIPTION
**Pull request by N1ghtMoon**

### CODE REVIEW

**Comment by brian0305** [comment]
why use game.ping in thiss ?

**Comment by N1ghtMoon** [comment]
When your ping > 120, it was so suck, (move up Animation)

these day i enjoy my high ping games to play garena and i test it a long times about riven

**Comment by brian0305** [comment]
who the fuk play lol with that ping :D

**Comment by nabbhacker** [comment]
My broscience finder is tingling.

**Comment by h3h3** [comment]
^

**Comment by N1ghtMoon** [comment]
when you play others server...  fuking CN server you just only play 1 - 2 games and get banned

**Pull request closed without merging**
