### PR TITLE
 TW  CN

### PR DESCRIPTION
**Pull request by CjShu**
Taiwan = Unicode 
China = Utf8

### CODE REVIEW

**Comment by CjShu** [comment]
I L# ID  CjShu

**Comment by ghost** [comment]
Hello and thanks for contributing to LeagueSharp.
Unfourtunately the changes you have requested are too many for me to check.
Could you possibly tell me which PR's you'd like merged or make a new PR with all the changes, or if the changes you made are the same as in here https://github.com/CjShu/TwLS.SDK/ and I can merge those instead?
Thanks and hope you have a nice day!

**Comment by CjShu** [comment]
Conversion is the same。 But because。 SDKEx／  SDK。  Both can be used under normal

**Comment by CjShu** [comment]
Translation resources , will update later , it takes time to do the translation

**Comment by CjShu** [comment]
Other places do not affect

**Comment by CjShu** [comment]
Two national language，  Differences，The need for such conversion

**Comment by CjShu** [comment]
OK PR two are my account

**Comment by CjShu** [comment]
You can take. He took it all away because of the translation language. After this success .                 Last only need to update the resource file .Often add new translation language .Other files will not affect your development of new things. I just want to contribute to the local Taiwan and China to see our language

**Comment by CjShu** [comment]
Resource translation is a language that requires a long time to be translated, so we will submit it to you for a while. .The new translation submitted to you

**Comment by CjShu** [comment]
Hope that the official will be able to recognize the language of Taiwan    OR CN language   .The difference between the two

**Comment by brian0305** [comment]
hello @as112200 ty for contribute our project. But can you pls next time put everything into 1 PR ?
Code ~> Test ~> PR !!! Ty

**Comment by CjShu** [comment]
Ok.  Sorry

**Comment by CjShu** [comment]
That day I was using a web page
Upload submit pr
He can not submit a one-time
sorry

**Comment by ghost** [comment]
noticed. it's np, thanks for your hard work guys!

**Pull request merged**
