### PR TITLE
Update LeagueSharp.SDKEx.csproj

### PR DESCRIPTION
**Pull request by CjShu**

### CODE REVIEW

**Comment by ghost** [comment]
the used namespace is still LeagueSharp.SDK, not SDKEx for backward compability reasons :P

**Comment by CjShuMoon** [comment]
If replaced  SDK=SDKEx  ok  
Or into SDK=SDKEx

**Comment by CjShuMoon** [comment]
Because SDKEx
With SDK
Assembly components are almost all SDK
Other authors have not updated to SDKEx

**Comment by CjShuMoon** [comment]
The language conversion Ichishi
Mainly to name  SDK?  or SDKEx?

**Comment by ghost** [comment]
we will keep using the namespace name "LeagueSharp.SDK" so developers only have to change the csproj reference include="LeagueSharp.SDK" > LeagueSharp.SDKEx

**Comment by CjShuMoon** [comment]
If replaced SDKEx 
You will need to notify the author of the conversion of named SDKEx

**Comment by CjShuMoon** [comment]
Thank you ^^

**Comment by CjShu** [comment]
You try this is normal. 

If converted into SDKEx  .He must ask for one to

**Comment by CjShu** [comment]
Because .previously .edition He has SDKEx +SDK  =Cause error

**Comment by CjShu** [comment]
So we can only choose one

**Comment by as112200** [comment]
<RootNamespace>LeagueSharp.SDK</RootNamespace>
    <AssemblyName>LeagueSharp.SDKEx</AssemblyName>  Error

<RootNamespace>LeagueSharp.SDKEx</RootNamespace>
    <AssemblyName>LeagueSharp.SDKEx</AssemblyName>    ok 
<RootNamespace>LeagueSharp.SDK</RootNamespace>
    <AssemblyName>LeagueSharp.SDK</AssemblyName>   ok

**Pull request closed without merging**
