### PR TITLE
Add more translation

### PR DESCRIPTION
**Pull request by CjShu**
Add more translation
L#. script.
dodge
Champion Skills
Complete
Fixed some.
word
Great . small . Write provisions
neat
: )

### CODE REVIEW

**Comment by CjShu** [comment]
CN : Translator : LOVETAIWAN
Garena TW : Translator  : CjShu

**Comment by brian0305** [comment]
Nice thanks!

**Comment by CjShu** [comment]
No??

**Comment by ghost** [comment]
Thank you friends

**Comment by CjShu** [comment]
Careless by mistake
Thank you

**Comment by CjShu** [comment]
Multi case to SORRY

**Comment by CjShu** [comment]
my friend : chienhao10 . He will be in charge of CN .Translation
I will maintain Garena. Translation

**Pull request merged**
